baseurl = "https://themes.gohugo.io"

[module]
  [module.hugoVersion]
    min = "0.145.0"
  [[module.mounts]]
    source = "layouts"
    target = "layouts"
  [[module.mounts]]
    source = "content"
    target = "content"
  [[module.imports]]
    path = "github.com/gohugoio/hugoDocs"
    # We share the theme with the docs site, but we need to be explicit about
    # the mounts to avoid pulling in the content.
    [[module.imports.mounts]]
      source = "layouts"
      target = "layouts"
    [[module.imports.mounts]]
      source = "assets"
      target = "assets"
    [[module.imports.mounts]]
      source = "static"
      target = "static"
    [[module.imports.mounts]]
      source = "data"
      target = "data"
    [[module.imports.mounts]]
      source = "i18n"
      target = "i18n"
