[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.21"
  HUGO_ENV = "production"

# https://www.netlify.com/blog/2017/04/11/netlify-plus-hugo-0.20-and-beyond/
# https://www.netlify.com/docs/continuous-deployment/#deploy-contexts
